### ISSUE TITLE
uglify compile error

### ISSUE THREAD

**Issue by danielghost** [cgkineo/adapt-xAPI#18]
When compiling the build with a command that uglifies the files, `fetch-polyfill` causes an error due to the following code:
https://github.com/cgkineo/adapt-xAPI/blob/master/libraries/fetch-polyfill.js#L459

This should be changed as follows:
```javascript
var abortXhr = function() {
```

**Comment by moloko** [comment]
if you bump the FW to a more recent version, you might not need that polyfill?

**Comment by danielghost** [comment]
The compiling error is seemingly no longer an issue.

Whilst the polyfill is no longer needed for earlier browsers such as IE11 (which is no longer supported), it is still required as a fallback for Firefox which doesn't support the `keepalive` attribute, causing data sent on closing the browser to be potentially lost.
